# Generated by Django 3.1.7 on 2021-02-25 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Route name')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_transporter_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Small Transporter Size')),
                ('medium_transporter_size', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Medium Transporter Size')),
                ('big_transporter_size', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Big Transporter Size')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Station name')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', related_query_name='station', to='Management.route')),
            ],
            options={
                'unique_together': {('name', 'route')},
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name="Soldier's ID")),
                ('first_name', models.CharField(max_length=50, verbose_name="Soldier's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Soldier's last name")),
                ('phone', models.CharField(max_length=20, verbose_name="Soldier's phone")),
                ('city', models.CharField(max_length=20, verbose_name="Soldier's city")),
                ('structure', models.CharField(max_length=255, verbose_name="Soldier's structure")),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', related_query_name='soldier', to='Management.station', verbose_name="Soldier's station")),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='City name')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', related_query_name='city', to='Management.station')),
            ],
        ),
    ]
