# Generated by Django 3.1.7 on 2021-02-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=20, verbose_name="Soldier's ID")),
                ('first_name', models.CharField(max_length=50, verbose_name="Soldier's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Soldier's last name")),
                ('phone', models.CharField(max_length=20, verbose_name="Soldier's phone")),
                ('structure', models.CharField(max_length=255, verbose_name="Soldier's structure")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', related_query_name='soldier', to='Management.city')),
            ],
        ),
    ]
