# Generated by Django 3.1.7 on 2021-02-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('number', models.IntegerField()),
                ('platform', models.IntegerField(unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporters', related_query_name='transporter', to='Management.station')),
            ],
            options={
                'unique_together': {('size', 'number', 'station')},
            },
        ),
    ]
