# Generated by Django 3.1.7 on 2021-02-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', related_query_name='station', to='Management.route')),
            ],
            options={
                'unique_together': {('name', 'route')},
            },
        ),
    ]
