# Generated by Django 3.1.7 on 2021-02-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_transporter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transporter',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TransporterForCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.station')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.transporter')),
            ],
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='station',
        ),
        migrations.AddField(
            model_name='transporter',
            name='stations',
            field=models.ManyToManyField(related_name='transporters', related_query_name='transporter', through='Management.TransporterForCity', to='Management.Station'),
        ),
    ]
