# Generated by Django 3.1.7 on 2021-02-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210226_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterforcity',
            name='occupied_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporterforcity',
            name='soliders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Management.soldier'),
        ),
    ]
